version: '3'

services:
  app:
    build: .
    container_name: python
    command: make start
    depends_on:
      - db
    
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    container_name: db
