version: '3'

services:
  python_app:
    build: .
    container_name: python_app
    command: poetry run python app/models.py
    volumes:
      - .:/app/
    environment:
      - DOCKER_ENV=true
    depends_on:
      - db
    
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    container_name: db

