version: '3'

services:
  python_app:
    build: .
    container_name: python_app
    command: poetry run python app/models.py
    volumes:
      - .:/app/
    depends_on:
      - db
    
  db:
    image: postgres
    env_file:
      - .env
    container_name: db

